apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cv
  labels:
    app: test-cv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-cv
  template:
    metadata:
      labels:
        app: test-cv
    spec:
      containers:
      - name: test-cv
        image: IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "test-cv.settings"